export const icons = [
{ label : "Aframe",
    imgSrc : "/icons/Aframe.svg" },
{ label : "Amazing",
    imgSrc : "/icons/Amazing.svg" },
{ label : "BeachView",
    imgSrc : "/icons/Beach.svg" },    
{ label : "BoatHouse",
    imgSrc : "/icons/BoatHouse.svg" },
{ label : "CaveHouse" ,
    imgSrc : "/icons/Cave.svg" },
{ label : "CityView",
    imgSrc : "/icons/City.svg"},
{ label : "DesertView",
    imgSrc : "/icons/Desert.svg"},
{ label : "Design",
    imgSrc : "/icons/Design.svg"},
{ label : "FarmHouse",
    imgSrc : "/icons/FarmHouse.svg"},
{ label : "GlassHouse",
    imgSrc : "/icons/Glass.svg"},
{ label : "IslandHouse",
    imgSrc : "/icons/Island.svg"},
{ label : "LakeView",
    imgSrc : "/icons/Lake.svg"},
{ label : "LuxuryHouse",
    imgSrc : "/icons/Luxury.svg"},
{ label : "MountainView",
    imgSrc : "/icons/Mountain.svg"},
{ label : "RiverView",
    imgSrc : "/icons/River.svg"},
{ label : "TentHouse",
    imgSrc : "/icons/Tent.svg"},
{ label : "TinyHouse",
    imgSrc : "/icons/Tiny.svg"},
{ label : "Traditional",
    imgSrc : "/icons/Traditional.svg"},
{ label : "TreeHouse",
    imgSrc : "/icons/TreeHouse.svg"},
{ label : "UnderWater" ,
    imgSrc : "/icons/UnderWater.svg"},
];

